{
  description = "machine0 CLI — Cloud VMs from the CLI (Nix package)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # --- pin (updated by ./update.sh) ---
        version = "1.0.148";
        hash = "sha256-nqQEvZjmE7NiyDEIz3DERRgKEfArRqM9rHZTtvNVB6s=";
        npmDepsHash = "sha256-QecaJnJs5vNY47GYG4j/wBblbOTIh1klOeUrqrMS1ds=";
        # -------------------------------------

        machine0 = (pkgs.buildNpmPackage.override { nodejs = pkgs.nodejs_22; }) {
          pname = "machine0-cli";
          inherit version npmDepsHash;

          src = pkgs.fetchurl {
            url = "https://registry.npmjs.org/@machine0/cli/-/cli-${version}.tgz";
            inherit hash;
          };

          # The published package.json carries devDependencies with bun
          # `workspace:*` refs that npm cannot parse, and its runtime deps
          # (open, update-notifier) are deliberately external to the JS bundle.
          # Strip the devDependencies and install just the runtime tree from
          # the vendored lockfile (regenerated by ./update.sh on every bump).
          postPatch = ''
            ${pkgs.jq}/bin/jq 'del(.devDependencies)' package.json > package.json.tmp
            mv package.json.tmp package.json
            cp ${./package-lock.json} package-lock.json
          '';

          # The tarball ships a prebuilt bundle; there is nothing to build.
          dontNpmBuild = true;

          meta = with pkgs.lib; {
            description = "machine0 CLI — cloud VMs from the command line";
            homepage = "https://machine0.io";
            mainProgram = "machine0";
            platforms = platforms.unix;
          };
        };
      in {
        packages.default = machine0;
        packages.machine0 = machine0;
        apps.default = { type = "app"; program = "${machine0}/bin/machine0"; };
      });
}
